### PR TITLE
:recycle: Updated to the new Vue standards

### LINKED ISSUE #10: :arrow_up: Update to Vite Tooling

### PR DESCRIPTION
**Pull request by Sigmanificient**

### CODE REVIEW

**Comment by Arthurdw** [comment]
My knowledge of vue: 0.3%
Aka I'm not permitted to review this hahahah

**Comment by trag1c** [comment]
> My knowledge of vue: 0.3% Aka I'm not permitted to review this hahahah

same

**Comment by Sigmanificient** [comment]
Ah xD

**Comment by Sigmanificient** [comment]
Basically site dependencies based where very old, so i updated them to fix

**Pull request merged**
